<a href="https://colab.research.google.com/github/giridharpalla/python_ds/blob/main/NumPy_Tutorial_Annotated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


### The Basics

In [ ]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.
- `dtype='int32'` sets the type of the array elements.


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.


In [ ]:
# Get Dimension
a.ndim

1

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `.ndim` returns the number of dimensions.


In [ ]:
# Get Shape
b.shape

(2, 3)

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `.shape` returns the dimensions of the array (rows, columns).


In [ ]:
# Get Type
a.dtype

dtype('int32')

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `dtype='int32'` sets the type of the array elements.


In [ ]:
# Get Size
a.itemsize

4

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `.itemsize` returns the size in bytes of each element.


In [ ]:
# Get total size
a.nbytes

12

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `.nbytes` returns the total memory consumed by the array.


In [ ]:
# Get number of elements
a.size

3

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `.size` gives the total number of elements.


### Accessing/Changing specific elements, rows, columns, etc

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.


In [ ]:
# Get a specific element [r, c]
a[1, 5]

13

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


*3-d example

In [2]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.


In [4]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
# replace
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence.

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


### Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.zeros()` creates an array filled with 0s.


In [5]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `dtype='int32'` sets the type of the array elements.
- `np.ones()` creates an array filled with 1s.


In [8]:
# Any other number
s= np.full((3,2,2), 99)

In [10]:
s

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.full()` creates an array filled with a specified value.


In [13]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.full()` creates an array filled with a specified value.


In [ ]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.random.rand()` generates an array with random floats between 0 and 1.


In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2, -4, -4],
       [ 6,  6,  3],
       [ 3,  2,  2]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.random.rand()` generates an array with random floats between 0 and 1.
- `np.random.randint()` generates random integers in a given range.


In [17]:
# The identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.identity()` creates an identity matrix.


In [18]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.zeros()` creates an array filled with 0s.
- `np.ones()` creates an array filled with 1s.


##### Be careful when copying arrays!!!

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.


### Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.


In [ ]:
a + 2

array([5, 6, 7, 8])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
a - 2

array([-1,  0,  1,  2])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
a * 2

array([2, 4, 6, 8])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
b = np.array([1,0,1,0])
a + b

array([1, 0, 3, 0])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.


In [ ]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


##### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.ones()` creates an array filled with 1s.
- `np.full()` creates an array filled with a specified value.
- `np.matmul()` performs matrix multiplication.


In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.identity()` creates an identity matrix.
- `np.linalg.det()` calculates the determinant of a matrix.


In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


##### Statistics

In [19]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.


In [20]:
np.min(stats)

np.int64(1)

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.min()` gets the minimum value.


In [22]:
np.max(stats, axis=1)

array([3, 6])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.max()` gets the maximum value.


In [29]:
print(np.sum(stats, axis=0))
print(stats)

[5 7 9]
[[1 2 3]
 [4 5 6]]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.sum()` sums elements of an array.


### Reorganizing Arrays

In [32]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.
- `.reshape()` changes the shape of the array without changing its data.


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.array([...])` creates a NumPy array.
- `np.vstack()` vertically stacks arrays.


In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.zeros()` creates an array filled with 0s.
- `np.ones()` creates an array filled with 1s.
- `np.hstack()` horizontally stacks arrays.


### Miscellaneous
##### Load Data from File

In [16]:
import numpy as np
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int16')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
- `np.genfromtxt()` loads data from a text file.


##### Boolean Masking and Advanced Indexing

In [19]:
(~((filedata > 50) & (filedata < 10)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:


### 🔍 Explanation:
This code demonstrates a basic NumPy operation. Let’s break it down below:
